from django.urls import path

from sms import views

urlpatterns=[
    path('', views.mainpg, name='mainpg'),
    path('logincode', views.logincode, name='logincode'),
    path('add_prod', views.add_prod, name='add_prod'),
    path('ctgry', views.ctgry, name='ctgry'),
    path('cat_list', views.cat_list, name='cat_list'),
    path('addcat', views.addcat, name='addcat'),
    path('update_prod/<int:id>', views.update_prod, name='update_prod'),
    path('update', views.update, name='update'),
    path('delete_prod/<int:id>', views.delete_prod, name='delete_prod'),
    path('dis_reg', views.dis_reg, name='dis_reg'),
    path('admin_hom', views.admin_hom, name='admin_hom'),
    path('bill_pg', views.bill_pg, name='bill_pg'),
    path('bill_pg2/<int:id>', views.bill_pg2, name='bill_pg2'),
    path('complt_pg', views.complt_pg, name='complt_pg'),
    path('complt_pg1', views.complt_pg1, name='complt_pg1'),
    path('retn2', views.retn2, name='retn2'),
    path('retn1', views.retn1, name='retn1'),
    path('returned/<int:id>',views.returned,name='returned'),

    path('cmplt', views.cmplt, name='cmplt'),
    path('addcmplt', views.addcmplt, name='addcmplt'),
    path('viewreply', views.viewreply, name='viewreply'),
    path('dis_hom', views.dis_hom, name='dis_hom'),
    path('feedb_pg', views.feedb_pg, name='feedb_pg'),
    path('fdbk', views.fdbk, name='fdbk'),
    path('blockshop/<int:id>', views.blockshop, name='blockshop'),
    path('unblockshop/<int:id>', views.unblockshop, name='unblockshop'),
    path('block/<int:id>', views.block, name='block'),
    path('unblock/<int:id>', views.unblock, name='unblock'),
    path('block_or_unblock_shop', views.block_or_unblock_shop, name='block_or_unblock_shop'),
    path('block_or_unblock_dis', views.block_or_unblock_dis, name='block_or_unblock_dis'),
    path('mng_shop', views.mng_shop, name='mng_shop'),
    path('odr_pg/<int:id>', views.odr_pg, name='odr_pg'),
    path('prd_list', views.prd_list, name='prd_list'),
    path('rply_pg/<int:id>', views.rply_pg, name='rply_pg'),
    path('rpt', views.rpt, name='rpt'),
    path('sendreply', views.sendreply, name='sendreply'),
    path('searchandviewprdcts', views.searchandviewprdcts, name='searchandviewprdcts'),
    path('orderproduct', views.orderproduct, name='orderproduct'),
    path('acceptorder/<int:id>', views.acceptorder, name='acceptorder'),
    path('rejectorder/<int:id>', views.rejectorder, name='rejectorder'),
    path('aprv/<int:id>', views.aprv, name='aprv'),
    path('rjt/<int:id>', views.rjt, name='rjt'),
    path('paymnt_1/<int:id>',views.paymnt_1,name='paymnt_1'),
    path('paymnt_2', views.paymnt_2, name='paymnt_2'),
    path('retn', views.retn, name='retn'),
    path('sale_list', views.sale_list, name='sale_list'),
    path('send_fb', views.send_fb, name='send_fb'),
    path('shop_hom', views.shop_hom, name='shop_hom'),
    path('shop_reg', views.shop_reg, name='shop_reg'),
    path('shop_add_prd', views.shop_add_prd, name='shop_add_prd'),
    path('shop_prd', views.shop_prd, name='shop_prd'),
    path('shop_list', views.shop_list, name='shop_list'),
    path('view_dis', views.view_dis, name='view_dis'),
    path('view_shop', views.view_shop, name='view_shop'),
    path('shoprpt', views.shoprpt, name='shoprpt'),
    path('logins', views.logins, name='logins'),
    path('viewodr', views.viewodr, name='viewodr'),
    path('disbtr', views.disbtr, name='disbtr'),
    path('shpownr', views.shpownr, name='shpownr'),
    path('logout', views.logout, name='logout'),
    path('user_order1', views.user_order1, name='user_order1'),
    path('user_order2', views.user_order2, name='user_order2'),
    path('user_order3/<int:id>', views.user_order3, name='user_order3'),
    path('order_info', views.order_info, name='order_info'),
    path('paymt', views.paymt, name='paymt'),
    path('on_payment_success',views.on_payment_success,name='on_payment_success'),

    path('prdct', views.prdct, name='prdct'),
    path('accept/<int:id>', views.accept, name='accept'),
    path('reject/<int:id>', views.reject, name='reject'),
    path('acceptshop/<int:id>', views.acceptshop, name='acceptshop'),
    path('rejectshop/<int:id>', views.rejectshop, name='rejectshop'),
    path('stock_info', views.stock_info, name='stock_info'),
    # path('editshop/<int:id>', views.editshop, name='editshop'),
    # path('deleteshop/<int:id>', views.deleteshop, name='deleteshop'),


]