# Generated by Django 4.0.6 on 2023-05-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dis_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=90)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=90)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('orderstatus', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shop_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=90)),
                ('MRP', models.IntegerField()),
                ('Tax', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='shop_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('mobile_number', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.login')),
            ],
        ),
        migrations.CreateModel(
            name='returnlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.order')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=90)),
                ('price', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.category')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.dis_registration')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.shop_registration'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.shop_registration')),
            ],
        ),
        migrations.AddField(
            model_name='dis_registration',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.login'),
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=300)),
                ('reply', models.CharField(max_length=90)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.dis_registration')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.shop_registration')),
            ],
        ),
        migrations.CreateModel(
            name='billdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.bill')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.order')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.shop_registration'),
        ),
    ]
