# Generated by Django 4.1.7 on 2023-03-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='did',
        ),
    ]
