# Generated by Django 4.1.7 on 2023-04-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_feedback_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='did',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sms.dis_registration'),
            preserve_default=False,
        ),
    ]
