# Generated by Django 4.1.7 on 2023-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Count',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
