# Generated by Django 4.1.7 on 2023-04-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_product_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=66),
            preserve_default=False,
        ),
    ]
