# Generated by Django 4.1.7 on 2023-04-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
